name: Deploy to Fly.io

on:
  push:
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Format code
        run: bun run format

      - name: Run linting
        run: bun run lint

      - name: Build app
        run: bun run build
        env:
          PUBLIC_APPWRITE_ENDPOINT: ${{ secrets.PUBLIC_APPWRITE_ENDPOINT }}
          PUBLIC_APPWRITE_PROJECT_ID: ${{ secrets.PUBLIC_APPWRITE_PROJECT_ID }}

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --build-arg PUBLIC_APPWRITE_ENDPOINT="${{ secrets.PUBLIC_APPWRITE_ENDPOINT }}" --build-arg PUBLIC_APPWRITE_PROJECT_ID="${{ secrets.PUBLIC_APPWRITE_PROJECT_ID }}"
